### PR TITLE
Ads.txt file exists check from backend side

### LINKED ISSUE #48: Ads.txt file detection does not take mapped domains into account
**Describe the bug**
If you use a mapped domain (i.e. your wp-admin is on a different domain from your site, like on WordPress.com), the ads.txt file detection looks for the file on the wp-admin domain, which can return a false positive. See https://wordpress.org/support/topic/existing-ads-txt-file-found/

**Steps to Reproduce**
I haven't actually done this yet, but my guess is:

1. Put an ads.txt in the root of a MS instance
2. Set up domain mapping for a subsite
3. Go to the ads.txt edit screen on the subsite
4. See notice that an existing ads.txt file was found

**Expected behavior**
I would not expect to see the notice.

**Screenshots**
n/a

**Environment information**
This is as of Ads.txt 1.2.0, seen on WordPress.com with a business plan where you can install plugins and map domains.

**Additional context**
Reported here: https://wordpress.org/support/topic/existing-ads-txt-file-found/

### PR DESCRIPTION
**Pull request by sksaju**
### Description of the Change

This PR fixes the https://github.com/10up/ads-txt/issues/48 issue, by adding ads.txt file check from the backend side

Closes #

### How to test the Change

- Put an ads.txt in the root of a MS instance
- Set up domain mapping for a subsite
- Go to the ads.txt edit screen on the subsite
- See notice that an existing ads.txt file was found

### Changelog Entry

> Added - ads.txt file exists check from backend side

### Credits

Props @sksaju, @mmcachran, @peterwilsoncc, @dinhtungdu, @helen, @jeffpaul. 

### Checklist:

- [ ] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

### CODE REVIEW

File: inc/admin.php [hunk 1]
```diff
@@ -269,6 +269,14 @@ function settings_screen( $post_id, $strings, $args ) {
 	}
 	?>
 <div class="wrap">
+	<?php if ( file_exists( ABSPATH . '/ads.txt' ) ) { ?>
```
Comment (peterwilsoncc) [inline inc/admin.php]: This check won't work I'm afraid.

`ABSPATH` points to the directory of the WordPress install, which isn't necessarily the same as the root directory of the website. See this guide for [running wordpress in a subdirectory](https://wordpress.org/documentation/article/giving-wordpress-its-own-directory/).

To use my site as an example, this would check for `/path/to/files/wp/ads.txt` rather than `/path/to/files/ads.txt`.

I think there would be some weirdness around multisite installs too.

Comment (sksaju) [reply inc/admin.php]: Yeah, that makes sense, I'll try to fix the issue

Comment (peterwilsoncc) [reply inc/admin.php]: I added a quick comment with some pseudo code on the original issue https://github.com/10up/ads-txt/issues/48#issuecomment-1459104883

Comment (sksaju) [reply inc/admin.php]: @peterwilsoncc I'm trying to check the file following your suggestions but somehow when I try to get the file via `wp_remote_request` request I'm getting empty headers data, I've pushed the latest changes on this branch, could you take a look, please? Thanks

Comment (peterwilsoncc) [reply inc/admin.php]: I'm unable to reproduce an error with empty headers, this is what I am seeing in xdebug using the file_exists line as a break point.

Screen Shot 2023-04-03 at 1 49 55 pm

**Comment by jeffpaul** [comment]
@sksaju there appears to be a merge conflict, mind resolving that and letting us know if this is ready for re-review?  Thanks!

File: inc/admin.php (hunk 1 above)
Comment (sksaju) [reply inc/admin.php]: Thanks @peterwilsoncc I was able to test header data today

This is the header response from ads.txt file
Screenshot 2023-04-26 at 8 56 17 PM

and this from adstxt post type
Screenshot 2023-04-26 at 8 56 30 PM

Can we check the file with the `Content-Length` and/or `ETag` properties as these are not present in the post-type response? although I don't have much experience with online server file systems, I think these might help to differentiate between file response and post-type response! please let me know your feedback. Thanks

**Comment by jeffpaul** [comment]
@peterwilsoncc back to you for review here

File: inc/admin.php [hunk 2]
```diff
@@ -509,3 +515,35 @@ function clean_orphaned_posts( $option, $post_type ) {
...
+function adstxts_check_for_existing_file() {
+	$home_url_parsed = wp_parse_url( home_url() );
+	if ( empty( $home_url_parsed['path'] ) ) {
+		$response   = wp_remote_request( home_url( '/ads.txt' ) );
+		$file_exist = false;
+		if ( ! is_wp_error( $response ) ) {
+			// Get the headers of the response
+			$headers      = wp_remote_retrieve_headers( $response );
+			$content_type = isset( $headers['content-type'] ) ? $headers['content-type'] : '';
+			$file_exist   = strpos( $content_type, 'application/octet-stream' ) !== false;
```
Comment (peterwilsoncc) [inline inc/admin.php]: While testing, I was getting a false report here (I had an ads.txt file but it wasn't detected). 

How about the adding `header( 'X-Ads-Txt-Generator: https://wordpress.org/plugins/ads-txt/' );` to the output in the main file (both for ads.txt and for app-ads.txt) and then checking for the header:

```suggestion
			// Check the ads.txt generator header.
			$headers    = wp_remote_retrieve_headers( $response );
			$generator  = isset( $headers['X-Ads-Txt-Generator'] ) ? $headers['X-Ads-Txt-Generator'] : '';
			$file_exist = 'https://wordpress.org/plugins/ads-txt/' !== $generator;
```

The generator header would need to be included regardless of whether the post exists or not, so probably right after the get_option() check in each block.

File: inc/admin.php [hunk 3]
```diff
@@ -509,3 +515,35 @@ function clean_orphaned_posts( $option, $post_type ) {
...
+
+/**
+ * Check if ads.txt file already exists in the server
+ *
+ * @return void
+ */
+function adstxts_check_for_existing_file() {
+	$home_url_parsed = wp_parse_url( home_url() );
+	if ( empty( $home_url_parsed['path'] ) ) {
+		$response   = wp_remote_request( home_url( '/ads.txt' ) );
```
Comment (peterwilsoncc) [inline inc/admin.php]: We'll need something here (and in the JS) to determine whether the check should be for ads.txt or app-ads.txt .

You can probably include something in the `admin_enqueue_scripts()` function within this file based on the hook -- whether it contains `app-adstxt`  or not.

To be secure you should send it in the form `is_appstxt: true|false` and modify the URL check based on the true false statement. Don't use the variable `home_url( $passed_value )` as someone could modify that to a random file name, such as `.env` or similar.

File: inc/admin.php [hunk 4]
```diff
@@ -509,3 +515,35 @@ function clean_orphaned_posts( $option, $post_type ) {
...
 	return true;
 }
+
+/**
+ * Check if ads.txt file already exists in the server
+ *
+ * @return void
+ */
+function adstxts_check_for_existing_file() {
+	$home_url_parsed = wp_parse_url( home_url() );
```
Comment (peterwilsoncc) [inline inc/admin.php:528]: Security: This will need both a nonce and a capability check, similar to that used in the save function:

https://github.com/10up/ads-txt/blob/dc18245c6add3f0eaeaafca83c2dc1d88ecd209c/inc/save.php#L19-L20

File: inc/admin.php [hunk 5]
```diff
@@ -509,3 +515,35 @@ function clean_orphaned_posts( $option, $post_type ) {
...
+		// Return the response
+		wp_send_json(
+			[
+				'success'    => true,
+				'file_exist' => $file_exist,
+			]
+		);
+
+		// Make sure to exit
+		wp_die();
```
Comment (peterwilsoncc) [inline inc/admin.php:557]: `wp_send_json()` exits.

```suggestion
```

**Review by peterwilsoncc — COMMENTED** [review]
I've added some notes inline. I'm not sure why the E2E tests are failing.

File: inc/admin.php [hunk 6]
```diff
@@ -272,6 +272,12 @@ function settings_screen( $post_id, $strings, $args ) {
 	clean_orphaned_posts( $post_id, $args['post_type'] );
 	?>
 <div class="wrap">
+	<div class="notice notice-error adstxt-notice existing-adstxt" style="display: none;">
+		<p><strong><?php echo esc_html( $strings['existing'] ); ?></strong></p>
+		<p><?php echo esc_html( $strings['precedence'] ); ?></p>
+
+		<p><?php echo esc_html_e( 'Removed the existing file but are still seeing this warning?', 'ads-txt' ); ?> <a class="ads-txt-rerun-check" href="#"><?php echo esc_html_e( 'Re-run the check now', 'ads-txt' ); ?></a> <span class="spinner" style="float:none;margin:-2px 5px 0"></span></p>
+	</div>
```
Comment (peterwilsoncc) [inline inc/admin.php:280]: Follow up: it's the presence of this that is causing the tests to fail. I pushed a fix in 5d9f27dfab8599b8d708d747a1e7647b71fb6794

**Review by peterwilsoncc — APPROVED** [review]
This looks good to me, thank you for your patience during the review process.

Testing notes:
* identical content in a real file and the generated version show the warning
* different content in a real file and the generated version show the warning
* the generated file includes the custom header
* file not found errors include the custom header
* accounts for built in Multisite domain mapping
